-- Coller dans Supabase > SQL Editor > New query

create table if not exists commandes (
  id bigint generated by default as identity primary key,
  bc text not null,
  ref text,
  fournisseur text,
  entite text,
  produit text,
  taille text,
  categorie text,
  qte_commandee integer default 0,
  qte_livree integer default 0,
  prix_u numeric default 0,
  livraison_prevue date,
  saison text default 'SS26',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists livraisons (
  id bigint generated by default as identity primary key,
  facture text not null,
  date_livraison date,
  transport text,
  entite text,
  fournisseur text,
  nb_lignes integer default 0,
  qte_totale integer default 0,
  montant_ht numeric default 0,
  saison text default 'SS26',
  notes text,
  created_at timestamptz default now()
);

-- Activer RLS (Row Level Security) en mode ouvert pour commencer
alter table commandes enable row level security;
alter table livraisons enable row level security;

create policy "Allow all" on commandes for all using (true) with check (true);
create policy "Allow all" on livraisons for all using (true) with check (true);
